Feature/job families
roisingoodman1/doras pull request #16
Opened 2019-11-07 15:40 UTC by PatrickWatson887

2019-11-07 15:57 UTC, micalexis requested changes
address the comments and squash your commits

2019-11-07 15:57 UTC, micalexis commented on Doras/src/app/carousel-tabs/carousel-tabs.component.html
> +      <p>{{capabilities}}</p>
this should be removed

2019-11-07 15:57 UTC, micalexis commented on Doras/src/app/carousel-tabs/carousel-tabs.component.ts
> +    console.log(this.capabilities);
this should be removed

2019-11-07 15:57 UTC, micalexis commented on Doras/src/app/carousel/carousel.component.ts
> +    let index = slideEvent.current.split('-')[2];
did we not discuss changing this from using the slide id to the actual DB id?

2019-11-07 15:57 UTC, micalexis commented on Doras/src/app/data.service.ts
> +  public getJobFamily(): Promise<JobFamily[]> {
follow one approach! refactor all endpoints to use Observables!

2019-11-07 15:57 UTC, micalexis commented on ExpressAPI/app.js
> +app.get('/getCapNameByJfId/:id', function(req, res) {
your express endpoints need to be RESTful, look into this!

2019-11-08 10:48 UTC, lukemciKainos approved these changes

2019-11-08 10:48 UTC, merged

2019-11-08 11:06 UTC, micalexis reviewed
make sure you squash your commits!!!!

2019-11-08 11:06 UTC, micalexis commented on Doras/src/app/roles/roles.component.html
> +                     class="th1" scope="col">{{endArray[i][0].bandName}}
what is endArray? give it a proper name

2019-11-08 11:06 UTC, micalexis commented on Doras/src/app/roles/roles.component.html
> +                                <h4 *ngIf="job1Title; else notShowBlock">{{job1Title}}</h4>
job1Title, job2Title, job3Title? why are we not looping over these? this needs to be refactored!!

2019-11-08 11:06 UTC, micalexis commented on Doras/src/app/roles/roles.component.ts
> +  public jobs1: Job[];
what do these refer to?

2019-11-08 11:06 UTC, micalexis commented on Doras/src/app/roles/roles.component.ts
> +      let array = []
where are the `;` at the end of each statement?